name: Sync Google Sheets to CSV (Keyless Auth)

on:
  # Scheduled trigger - daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'

  # Manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip PR creation)'
        required: false
        default: false
        type: boolean

# Required permissions
permissions:
  contents: write
  pull-requests: write
  id-token: write  # Required for OIDC token authentication

jobs:
  sync-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for better diffs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Keyless authentication using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: elastic/oblt-actions/google/auth@v1
        with:
          workload-identity-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # The auth action sets GOOGLE_APPLICATION_CREDENTIALS automatically
      - name: Run sync script
        env:
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
        run: |
          python sync_sheet.py --config config.yml --verbose

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet output/*.csv 2>/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in CSV files"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in CSV files"

            # Get row count from CSV (subtract 1 for header)
            if [ -f output/*.csv ]; then
              row_count=$(($(wc -l < output/*.csv) - 1))
              echo "row_count=${row_count}" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true' && github.event.inputs.dry_run != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create branch with timestamp
          branch_name="sheets-update-$(date +%Y-%m-%d-%H%M%S)"
          git checkout -b "$branch_name"

          # Stage and commit changes
          git add output/*.csv
          git commit -m "Update CSV from Google Sheets

          Generated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          Workflow run: ${{ github.run_number }}

          [skip ci]"

          # Push branch
          git push origin "$branch_name"

          # Get CSV filename
          csv_file=$(ls output/*.csv | head -n 1)
          csv_filename=$(basename "$csv_file")

          # Get row count
          row_count=${{ steps.check_changes.outputs.row_count }}
          col_count=$(head -n 1 "$csv_file" | awk -F',' '{print NF}')

          # Create PR with gh CLI
          gh pr create \
            --title "Update CSV from Google Sheets - $(date +%Y-%m-%d)" \
            --body "## Summary

          This PR updates the CSV file with the latest data from Google Sheets.

          **File:** \`${csv_filename}\`
          **Rows:** ${row_count}
          **Columns:** ${col_count}
          **Generated:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')

          ### Changes

          Please review the changes in the Files tab to ensure the data looks correct.

          ### Next Steps

          - [ ] Review the CSV changes
          - [ ] Verify data accuracy
          - [ ] Merge when ready

          ---

          ðŸ¤– Automated update from [sync-sheets workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
            --head "$branch_name" \
            --base main

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-csv-${{ github.run_number }}
          path: output/*.csv
          retention-days: 30
          if-no-files-found: warn

      - name: Generate job summary
        if: always()
        run: |
          echo "## Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Changes Detected:** ${{ steps.check_changes.outputs.changed }}" >> $GITHUB_STEP_SUMMARY
          echo "**Dry Run:** ${{ github.event.inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f output/*.csv ]; then
            echo "### Generated Files" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            ls -lh output/*.csv >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY

            # Show first few rows as preview
            echo "### Preview (first 5 rows)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`csv" >> $GITHUB_STEP_SUMMARY
            head -n 6 output/*.csv >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "âš ï¸ No CSV files found" >> $GITHUB_STEP_SUMMARY
          fi
