name: "Serverless UX bug bash issue"
description: Issues found in the Serverless Docs as part of the Serverless UX bug bash.
title: "[Serverless]: "
labels: ["Serverless bug bash :bug:"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request! This form will create an issue that the Docs team will triage and prioritize.

        ### For best results, complete all fields.
  - type: dropdown
    id: project-type
    attributes:
      label: Serverless Docs
      description: Select the Serverless Docs set this change impacts.
      options:
        - Welcome to Elastic Serverless
        - Elasticsearch
        - Elastic Observability
        - Elastic Security
        - Dev tools
        - Project and management settings
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue. 
      placeholder: |
        Provide a description of the issue you found.
        Describe the steps to reproduce the issue. 
        Describe the expected behavior.
        Provide screenshots of the issue.
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Resources and additional context
      description: Provide any resources and additional context for the Docs team to learn about the issue.
      placeholder: |
        There was a change implemented in {link_to_PR}.

        Context for the issue is described in {link_to_internal_doc}.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this form and improving the Serverless Docs.
