[[elasticsearch-billing]]
= Elasticsearch billing dimensions

// :description: Learn about how Elasticsearch usage affects pricing.
// :keywords: serverless, elasticsearch, overview

preview:[]

Elasticsearch is priced based on consumption of the underlying
infrastructure that supports your use case, with the performance
characteristics you need. Measurements are in Virtual Compute Units (VCUs).
Each VCU represents a fraction of RAM, CPU, and local disk for caching.

The number of VCUs required 
depends on the amount and rate of data sent to Elasticsearch and retained,
as well as the number of searches and the latency you require for searches. In addition, if
you use {ml} for inference or NLP tasks, those VCUs are also
metered and billed.

[discrete]
[[elasticsearch-billing-information-about-the-vcu-types-search-ingest-and-ml]]
== VCU types: Search, Ingest, and ML

Elasticsearch uses three VCU types:

* **Indexing:** The VCUs used to index incoming documents.
* **Search:** The VCUs used to return search results, with the latency and
queries per second (QPS) you require.
* **Machine learning:** The VCUs used to perform inference, NLP tasks, and other ML activities.

[discrete]
[[elasticsearch-billing-information-about-the-search-ai-lake-dimension-gb]]
== Search AI Lake dimension (GB)

Elasticsearch stores and retains data in the <<elasticsearch-manage-project-search-ai-lake-settings,Search AI Lake>>, 
which is charged in GB for the size of data at rest. Depending on enrichment,
vectorization, and other activities during ingest, this size may be different
from the original size of the source data.

[discrete]
[[elasticsearch-billing-managing-elasticsearch-costs]]
== Managing Elasticsearch costs

You can control costs by using a lower Search Power setting or reducing the amount 
of retained data. 

* **Search Power setting:** <<elasticsearch-manage-project-search-power-settings,Search Power>> controls the speed of searches against your data. With Search Power, you can 
improve search performance by adding more resources for querying, or you can reduce provisioned 
resources to cut costs.
* **Time series data retention:** By limiting the number of days of <<elasticsearch-ingest-time-series-data,time series data>> that are available for caching, 
you can reduce the number of search VCUs required. 

For detailed {es-serverless} project rates, see the https://www.elastic.co/pricing/serverless-search[{es-serverless} pricing page].
