[[elasticsearch-reference-semantic-search]]
= Semantic search

// :description: Find data based on the intent and contextual meaning of a search query with semantic search
// :keywords: elasticsearch, elser, semantic search

preview:[]

Semantic search is a search method that helps you find data based on the intent and contextual meaning of a search query, instead of a match on query terms (lexical search).

Elasticsearch provides various semantic search capabilities using natural language processing (NLP) and vector search. Using an NLP model enables you to extract text embeddings out of text. Embeddings are vectors that provide a numeric representation of a text. Pieces of content with similar meaning have similar representations.

image::images/semantic-options.svg[Overview of semantic search workflows in {es}]

[NOTE]
====
ℹ️ The Semantic search documentation currently lives in the https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search.html[Elasticsearch docs].
====

[discrete]
[[lasticsearch-reference-semantic-search-inference-api]]
== Semantic search with the inference API

The inference API workflow enables you to perform semantic search using models from a variety of services, such as Cohere, OpenAI, HuggingFace, Azure AI Studio, and more. 

[NOTE]
====
ℹ️ The Semantic search with the inference API documentation currently lives in the https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search-inference.html[Elasticsearch docs].
====

[discrete]
[[elasticsearch-reference-semantic-search-semantic-text]]
== Semantic search with `semantic text`

The `semantic_text` field simplifies semantic search by providing inference at ingestion time with sensible default values, eliminating the need for complex configurations. 

[NOTE]
====
ℹ️ The Semantic search with `semantic text` documentation currently lives in the https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search-semantic-text.html[Elasticsearch docs].
====

[discrete]
[[elasticsearch-reference-semantic-search-elser]]
== Semantic search with ELSER

Elastic Learned Sparse EncodeR - or ELSER - is an NLP model trained by Elastic
that enables you to perform semantic search by using sparse vector
representation. Instead of literal matching on search terms, semantic search
retrieves results based on the intent and the contextual meaning of a search
query.

[NOTE]
====
ℹ️ The Semantic search with ELSER documentation currently lives in the https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search-elser.html[Elasticsearch docs].
====
