name: Triage & route issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read

jobs:
  route:
    runs-on: ubuntu-latest
    if: >
      contains(
        [
          'team:Obs',
          'team:Security',
          'team:Platform',
          'team:DocsEng',
          'team:Projects'
        ],
        github.event.label.name
      )
    env:
      PROJECT_ID_MAP: |
        {
          "team:Obs":        "649",
          "team:Security":   "1034",
          "team:Platform":   "1232",
          "team:DocsEng":    "1625",
          "team:Projects":   "1415"
        }
    steps:
      - name: Remove needs-team label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: needs-team

      - name: Add issue to the right project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/elastic/projects/${{ fromJson(env.PROJECT_ID_MAP)[github.event.label.name] }}
          github-token: ${{ secrets.ADD_TO_BOARD_TOKEN }}
          labeled: ${{ github.event.label.name }}
          label-operator: OR
