name: Triage & route issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read
  projects: write

jobs:
  route:
    runs-on: ubuntu-latest
    if: >
      contains(
        [
          'team:obs',
          'team:security',
          'team:platform',
          'team:docs-eng',
          'team:docs-projects'
        ],
        github.event.label.name
      )
    env:
      PROJECT_ID_MAP: |
        {
          "team:obs":        "649",
          "team:security":   "1034",
          "team:platform":   "1232",
          "team:docs-eng":   "1625",
          "team:docs-projects": "1415"
        }
    steps:
      - name: Remove needs‑triage label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: needs-triage

      - name: Add issue to the right project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/elastic/projects/${{ fromJson(env.PROJECT_ID_MAP)[github.event.label.name] }}
          github-token: ${{ secrets.TRIAGE_TOKEN }}
          labeled: ${{ github.event.label.name }}
          label-operator: OR
