name: changelog-validate

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/changelog/**'

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
    uses: elastic/docs-actions/.github/workflows/changelog-validate.yml@v1
    with:
      config: changelog.yml
