name: docs-deploy

on:
  workflow_run:
    workflows: [docs-build]
    types:
      - completed

jobs:
  preview:
    uses: elastic/docs-builder/.github/workflows/preview-deploy.yml@main
    permissions:
      contents: none
      id-token: write
      deployments: write
      actions: read
