name: docs-build

on:
  push:
    branches:
      - main
  pull_request_target: ~

jobs:
  preview:
    uses: elastic/docs-builder/.github/workflows/preview-build.yml@feature/compression-level-test
    with:
      continue-on-error: false
      strict: false
      compression-level: 0
    permissions:
      deployments: write
      id-token: write
      contents: read
      pull-requests: read
